<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4yqHbuS\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4yqHbuS/srcProdProjectContainer.php') {
    touch(__DIR__.'/Container4yqHbuS.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\Container4yqHbuS\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \Container4yqHbuS\srcProdProjectContainer(array(
    'container.build_hash' => '4yqHbuS',
    'container.build_id' => '73711b01',
    'container.build_time' => 1521140840,
));
