<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry(array(0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Form\\AlunoType' => function () {
    return ($this->privates['App\Form\AlunoType'] ?? $this->privates['App\Form\AlunoType'] = new \App\Form\AlunoType());
}, 'App\\Form\\BannerType' => function () {
    return ($this->privates['App\Form\BannerType'] ?? $this->privates['App\Form\BannerType'] = new \App\Form\BannerType());
}, 'App\\Form\\ContentType' => function () {
    return ($this->privates['App\Form\ContentType'] ?? $this->privates['App\Form\ContentType'] = new \App\Form\ContentType());
}, 'App\\Form\\ImageType' => function () {
    return ($this->privates['App\Form\ImageType'] ?? $this->privates['App\Form\ImageType'] = new \App\Form\ImageType());
}, 'App\\Form\\MenuType' => function () {
    return ($this->privates['App\Form\MenuType'] ?? $this->privates['App\Form\MenuType'] = new \App\Form\MenuType());
}, 'App\\Form\\NewsLetterType' => function () {
    return ($this->privates['App\Form\NewsLetterType'] ?? $this->privates['App\Form\NewsLetterType'] = new \App\Form\NewsLetterType());
}, 'App\\Form\\PageType' => function () {
    return ($this->privates['App\Form\PageType'] ?? $this->privates['App\Form\PageType'] = new \App\Form\PageType());
}, 'App\\Form\\SubMenuType' => function () {
    return ($this->privates['App\Form\SubMenuType'] ?? $this->privates['App\Form\SubMenuType'] = new \App\Form\SubMenuType());
}, 'App\\Form\\TextType' => function () {
    return ($this->privates['App\Form\TextType'] ?? $this->privates['App\Form\TextType'] = new \App\Form\TextType());
}, 'App\\Form\\UsersType' => function () {
    return ($this->privates['App\Form\UsersType'] ?? $this->privates['App\Form\UsersType'] = new \App\Form\UsersType());
}, 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => function () {
    return ($this->privates['form.type.entity'] ?? $this->load(__DIR__.'/getForm_Type_EntityService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => function () {
    return ($this->privates['form.type.choice'] ?? $this->load(__DIR__.'/getForm_Type_ChoiceService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => function () {
    return ($this->privates['form.type.form'] ?? $this->load(__DIR__.'/getForm_Type_FormService.php'));
})), array('Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load(__DIR__.'/getForm_TypeExtension_Form_HttpFoundationService.php'));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? $this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? $this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
}, 1)), new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load(__DIR__.'/getForm_TypeGuesser_DoctrineService.php'));
}, 1))), ($this->privates['form.resolved_type_factory'] ?? $this->privates['form.resolved_type_factory'] = new \Symfony\Component\Form\ResolvedFormTypeFactory()));
