<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRCetuvB\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRCetuvB/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRCetuvB.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRCetuvB\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRCetuvB\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'RCetuvB',
    'container.build_id' => 'af6e34ff',
    'container.build_time' => 1522281111,
));
