<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJrsSaUJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJrsSaUJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJrsSaUJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJrsSaUJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJrsSaUJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JrsSaUJ',
    'container.build_id' => '44adb6ff',
    'container.build_time' => 1521139320,
));
